#! /bin/sh
### BEGIN INIT INFO
# Provides:          PiThermServer
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: 
# Description:       
### END INIT INFO

#
# cp NAME /etc/init.d/
# chmod 755 /etc/init.d/NAME
# update-rc.d NAME defaults
#

export PATH=$PATH:/opt/nodejs/bin

NAME=PiThermServer
DESC=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME
JS=/home/pi/PiThermServer/server.js
	
case "$1" in
	start)
		if [ -f $PIDFILE ]; then
			printf "Already started\n"
		else
			printf "%-50s" "Starting $NAME..."
			PID=`node $JS > /dev/null 2>&1 & echo $!`
			echo "Saving PID" $PID " to " $PIDFILE
			if [ -z $PID ]; then
				printf "%s\n" "Fail"
			else
				echo $PID > $PIDFILE
				printf "%s\n" "Ok"
			fi
		fi
	;;
	status)
# 		printf "%-50s" "Checking $NAME..."
		if [ -f $PIDFILE ]; then
			PID=`cat $PIDFILE`
			if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
				printf "%s\n" "Process dead but pidfile exists"
			else
				echo "Running"
			fi
		else
			printf "%s\n" "Not running"
		fi
	;;
	stop)
		printf "%-50s" "Stopping $NAME"
		PID=`cat $PIDFILE`
		cd $DAEMON_PATH
		if [ -f $PIDFILE ]; then
			kill -HUP $PID
			printf "%s\n" "Ok"
			rm -f $PIDFILE
		else
			printf "%s\n" "pidfile not found"
		fi
	;;

	restart)
		$0 stop
		$0 start
	;;
	
	*)
		echo "Usage: $0 {status|start|stop|restart}"
		exit 1
esac
exit 0
